# Generated by Django 4.2.2 on 2023-06-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_organizanion_name_organizationprofile_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organizanion_name',
        ),
    ]
