# Generated by Django 4.2.2 on 2023-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_manager_remove_user_organizanion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
    ]
