# Generated by Django 4.2.2 on 2023-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_organizationprofile_user_delete_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organisor',
        ),
    ]
