# Generated by Django 4.2.2 on 2023-06-27 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_alter_lead_comment_alter_lead_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='group',
            field=models.CharField(choices=[('New', 'Новый'), ('In progress', 'В работе'), ('Paid', 'Оплачен'), ('Done', 'Выполнен'), ('Rejected', 'Отказ')], default='Новый', max_length=25),
        ),
    ]
