# Generated by Django 4.2.2 on 2023-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
