# Generated by Django 4.2.2 on 2023-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_date_created_alter_lead_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
        migrations.AddField(
            model_name='lead',
            name='organization_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
