# Generated by Django 4.2.2 on 2023-07-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_organization_lead_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
