# Generated by Django 4.2.2 on 2023-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_organization_id_lead_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.CharField(default='NoneOrg', max_length=100),
        ),
    ]
