# Generated by Django 4.2.2 on 2023-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default='manager', max_length=30),
        ),
    ]
